# Generated by Django 4.1.1 on 2022-10-03 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["title"],
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ["title"],
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
            },
        ),
    ]
